name: Tpa
api: 4.0.0
version: 1.0
main: KurSkyTR\Tpa
author: EngincanErgunGG
description: "Oyuncuların birbirlerine ışınlanabilmesi için yapılmış ve kullanışlı bir eklenti."

commands:
  tpa:
    description: "Herhangi bir oyuncuya ışınlanma isteği gönderir."
    permission: "command.tpa"
  tpak:
    description: "Gelen ışınlanma isteğini kabul eder."
    permission: "command.tpak"
  tpar:
    description: "Gelen ışınlanma isteğini red eder."
    permission: "command.tpar"
  tpaistek:
    description: "Işınlanma isteklerini yönetir."
    permission: "command.tpaistek"

permissions:
  command.tpa:
    default: true
  command.tpak:
    default: true
  command.tpar:
    default: true
  command.tpaistek:
    default: true
